### ISSUE TITLE
winndows 7 64 bit compile failed.

### ISSUE THREAD

**Issue by liword** [XhstormR/GetBilibili-C#1]
-- The C compiler identification is GNU 6.3.0
-- Check for working C compiler: C:/MinGW/bin/gcc.exe
-- Check for working C compiler: C:/MinGW/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- GetBilibili-C
-- Found CURL: C:/Users/E7440/GetBilibili-C/curl/lib/libcurl.a (found version "7
.59.0-DEV")
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/E7440/GetBilibili-C/build
Scanning dependencies of target GetBilibili-C
[  9%] Building C object src/CMakeFiles/GetBilibili-C.dir/exec.c.obj
[ 18%] Building C object src/CMakeFiles/GetBilibili-C.dir/fio.c.obj
C:\Users\E7440\GetBilibili-C\src\fio.c:1:17: fatal error: ftw.h: No such file or
 directory
 #include <ftw.h>
                 ^
compilation terminated.
src\CMakeFiles\GetBilibili-C.dir\build.make:87: recipe for target 'src/CMakeFile
s/GetBilibili-C.dir/fio.c.obj' failed
mingw32-make[2]: *** [src/CMakeFiles/GetBilibili-C.dir/fio.c.obj] Error 1
CMakeFiles\Makefile2:84: recipe for target 'src/CMakeFiles/GetBilibili-C.dir/all
' failed
mingw32-make[1]: *** [src/CMakeFiles/GetBilibili-C.dir/all] Error 2
Makefile:128: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

**Comment by XhstormR** [comment]
没有 ftw.h 头文件，用最新的 mingw-w64 编译就行了。
