### ISSUE TITLE
此应用无法在你的电脑上运行

### ISSUE THREAD

**Issue by hcrgm** [XhstormR/GetBilibili-C#3]
当我执行命令后，系统弹窗如图所示。系统Windows 10版本1709，64位
![image](https://user-images.githubusercontent.com/11156348/36849380-e31da04a-1d9e-11e8-9e8c-b558a3190be5.png)

**Comment by XhstormR** [comment]
这就很迷了。。重新下载试试，也许是压缩包出错了。

**Comment by hcrgm** [comment]
我重新在cygwin环境里跑了一遍，仍旧弹窗，不过关闭弹窗后程序继续正常运行。不过GUI版本就直接闪退了

**Comment by XhstormR** [comment]
我是用 MinGW-w64 编译的，按理说不需要 Cygwin 环境，可以原生直接运行的。

**Comment by hcrgm** [comment]
运行确实不需要此环境。我觉得弹窗原因是因为那两个程序(aria2和ffmpeg)都是下载来的，而且都不能正常运行而导致弹窗，我只好手动下载那两个程序才能正常跑起来

**Comment by XhstormR** [comment]
可能是因为网络原因导致 aria2、ffmpeg 的下载出了出错了问题，变成了损坏的应用程序，所以 Windows 无法运行。我这里把缓存删除了，也无法复现。。
